pyallsky:
  image: allsky:latest
  user: 500:500
  environment:
      CONFIG_FILE = "/opt/camera-panel/etc/allsky_scheduler.conf"
  volumes:
    - "/opt/camera-panel/etc:/opt/camera-panel/etc"
    - "/mnt/data/allsky:/mnt/data/allsky"
  mem_limit: 8192m
  restart: always

